In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [3]:
df = pd.read_csv("veriler.csv")

In [4]:
df.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

In [30]:
ulke = df.iloc[:,0:1].values
ulke = ohe.fit_transform(ulke).toarray()
yas = df.iloc[:,1:4]
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [31]:
sonuc = pd.DataFrame(data = ulke,index=range(22),columns=['fr','tr','us'])
sonuc2 = pd.DataFrame(data=yas,index=range(22),columns=['boy','kilo','yas'])
sonuc3= pd.DataFrame(data=c[:,:1],index=range(22),columns=['cinsiyet'])

In [32]:
#encoder ----> cinsiyet icin c=cinsiyet
c = df.iloc[:,-1:].values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
c[:,0] = le.fit_transform(c[:,0])

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories='auto', sparse=True)
c = ohe.fit_transform(c).toarray()

In [33]:
s = pd.concat([sonuc,sonuc2],axis=1)
s2 = pd.concat([s,sonuc3],axis=1)

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [35]:
x_train

fr   tr   us  boy  kilo  yas
8   0.0  1.0  0.0  177    60   22
6   0.0  1.0  0.0  190    80   25
16  1.0  0.0  0.0  193    90   23
4   0.0  1.0  0.0  129    38   12
2   0.0  1.0  0.0  135    34   10
5   0.0  1.0  0.0  180    90   30
17  1.0  0.0  0.0  187    80   27
9   0.0  0.0  1.0  185   105   33
7   0.0  1.0  0.0  175    90   35
18  1.0  0.0  0.0  183    88   28
3   0.0  1.0  0.0  133    30    9
0   0.0  1.0  0.0  130    30   10
15  1.0  0.0  0.0  174    70   47
12  0.0  0.0  1.0  160    58   39

In [36]:
x_test

fr   tr   us  boy  kilo  yas
20  1.0  0.0  0.0  164    66   32
10  0.0  0.0  1.0  165    55   27
14  0.0  0.0  1.0  167    62   55
13  0.0  0.0  1.0  162    59   41
1   0.0  1.0  0.0  125    36   11
21  1.0  0.0  0.0  166    56   42
11  0.0  0.0  1.0  155    50   44
19  1.0  0.0  0.0  159    40   29

In [37]:
y_test

cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0

In [38]:
y_train

cinsiyet
8        0.0
6        1.0
16       1.0
4        1.0
2        0.0
5        1.0
17       1.0
9        1.0
7        1.0
18       1.0
3        0.0
0        1.0
15       1.0
12       0.0

In [39]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
y_pred

array([[ 0.98720204],
       [-0.12036863],
       [ 0.05009703],
       [ 0.07137418],
       [ 0.72473935],
       [ 0.64615044],
       [-0.03567453],
       [ 0.32612171]])

In [40]:
y_test

cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0

In [41]:
boy = s2.iloc[:,3:4].values
boy_sag = s2.iloc[:,:3]
boy_sol = s2.iloc[:,4:]
df_boy = pd.concat([boy_sag,boy_sol],axis=1)
df_boy

fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [42]:
x_train,x_test,y_train,y_test = train_test_split(df_boy,boy,test_size=0.33,random_state=0)

In [43]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
y_pred = lr.predict(x_test)

In [45]:
y_pred

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

In [46]:
y_test

array([[164],
       [165],
       [167],
       [162],
       [125],
       [166],
       [155],
       [159]])

In [47]:
df_boy

fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [48]:
#Backword elimination
import statsmodels.api as sm
X = np.append(arr = np.ones((22,1)).astype(int),values=df_boy,axis=1)
X_l = df_boy.iloc[:,[0,1,2,3,4,5]].values
r_ols = sm.OLS(endog = boy , exog = X_l)
r = r_ols.fit()
r.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Mon, 30 Mar 2020   Prob (F-statistic):           5.41e-07
Time:                        09:21:59   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.000      96.802     131.335
x2           108.3030      5.736     18.880      0.000      96.143     120.463
x3           104.4714      9.195     11.361      0.000      84.978     123.964
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6           -10.5980      5.052     -2.098      0.052     -21.308       0.112
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         524.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
## x5 and x6 have to be remove
df_boy_yeni = df_boy.iloc[:,:4]

In [50]:
x_train,x_test,y_train,y_test = train_test_split(df_boy_yeni,boy,test_size=0.33,random_state=0)

In [51]:
lr.fit(x_train,y_train)
new_prediction = lr.predict(x_test)

In [52]:
new_prediction

array([[170.90273989],
       [150.39360044],
       [156.23302674],
       [153.73041546],
       [139.02382298],
       [162.56070232],
       [146.22258165],
       [149.2134422 ]])

In [53]:
y_test

array([[164],
       [165],
       [167],
       [162],
       [125],
       [166],
       [155],
       [159]])