In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('veriler.csv')

In [3]:
df.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

In [4]:
x = df.iloc[:,1:4].values
y = df.iloc[:,4:].values

In [5]:
x

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]])

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()
print(x)
y

[[-1.62018668 -1.47588873 -1.47217295]
 [-1.86299395 -1.20033383 -1.39337051]
 [-1.37737941 -1.29218547 -1.47217295]
 [-1.47450232 -1.47588873 -1.5509754 ]
 [-1.66874813 -1.1084822  -1.31456806]
 [ 0.807886    1.27966024  0.10387595]
 [ 1.29350054  0.82040208 -0.29013628]
 [ 0.56507873  1.27966024  0.49788818]
 [ 0.66220164 -0.09811424 -0.52654361]
 [ 1.05069327  1.96854749  0.34028329]
 [ 0.0794642  -0.32774333 -0.13253139]
 [-0.40615034 -0.55737241  1.20711018]
 [-0.16334307 -0.18996588  0.81309796]
 [-0.06622016 -0.14404006  0.97070285]
 [ 0.1765871  -0.00626261  2.07393708]
 [ 0.51651728  0.36114392  1.44351752]
 [ 1.4391849   1.27966024 -0.44774117]
 [ 1.14781618  0.82040208 -0.13253139]
 [ 0.95357036  1.18780861 -0.05372894]
 [-0.21190452 -1.01663057  0.02507351]
 [ 0.03090274  0.17744065  0.26148084]
 [ 0.12802565 -0.28181751  1.04950529]]


array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=1)

In [8]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10,criterion='entropy')
rfc.fit(x_train,y_train)
y_pred = rfc.predict(x_test)
print('accuracy score ----> ', rfc.score(x_test,y_test))

accuracy score ---->  0.75


In [9]:
rfc1 = RandomForestClassifier(n_estimators=100,criterion='entropy')
rfc1.fit(x_train,y_train)
y_pred1 = rfc1.predict(x_test)
print('accuracy score ----> ', rfc1.score(x_test,y_test))

accuracy score ---->  0.875


In [10]:
rfc2 = RandomForestClassifier(n_estimators=10,criterion='gini')
rfc2.fit(x_train,y_train)
y_pred2 = rfc2.predict(x_test)
print('accuracy score ----> ', rfc2.score(x_test,y_test))

accuracy score ---->  0.75


In [11]:
rfc3 = RandomForestClassifier(n_estimators=100,criterion='gini')
rfc3.fit(x_train,y_train)
y_pred3 = rfc3.predict(x_test)
print('accuracy score ----> ', rfc3.score(x_test,y_test))

accuracy score ---->  0.875
