In [7]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

In [8]:
df = pd.read_csv('Wine.csv')

In [9]:
df.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [10]:
x = df.iloc[:,:13].values
y = df.iloc[:,13].values

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(x)

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [13]:
#PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_train2 = pca.fit_transform(x_train)
x_test2 = pca.transform(x_test)

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier2 = LogisticRegression(random_state=0)

In [15]:
classifier.fit(x_train,y_train)
classifier2.fit(x_train2,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
y_pred = classifier.predict(x_test)
y_pred2 = classifier2.predict(x_test2)

In [18]:
from sklearn.metrics import accuracy_score
ac_score = accuracy_score(y_test,y_pred)
ac_score1 = accuracy_score(y_test,y_pred2)
ac_score2 = accuracy_score(y_pred2,y_pred)

In [26]:
ac_scores = [ac_score,ac_score1,ac_score2]
for i in ac_scores:
    print(i)

0.9830508474576272
0.6779661016949152
0.6610169491525424


In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm1 = confusion_matrix(y_test,y_pred2)
cm2 = confusion_matrix(y_pred2,y_pred)

In [25]:
cms = [cm,cm1,cm2]
for i in cms:
    print(i)

[[20  0  0]
 [ 1 23  0]
 [ 0  0 15]]
[[20  0  0]
 [ 0 16  8]
 [ 1 10  4]]
[[20  0  1]
 [ 1 15 10]
 [ 0  8  4]]
