In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv("veriler.csv")

In [3]:
x = df.iloc[:,1:4].values
y = df.iloc[:,4:].values

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(x)

array([[-1.62018668, -1.47588873, -1.47217295],
       [-1.86299395, -1.20033383, -1.39337051],
       [-1.37737941, -1.29218547, -1.47217295],
       [-1.47450232, -1.47588873, -1.5509754 ],
       [-1.66874813, -1.1084822 , -1.31456806],
       [ 0.807886  ,  1.27966024,  0.10387595],
       [ 1.29350054,  0.82040208, -0.29013628],
       [ 0.56507873,  1.27966024,  0.49788818],
       [ 0.66220164, -0.09811424, -0.52654361],
       [ 1.05069327,  1.96854749,  0.34028329],
       [ 0.0794642 , -0.32774333, -0.13253139],
       [-0.40615034, -0.55737241,  1.20711018],
       [-0.16334307, -0.18996588,  0.81309796],
       [-0.06622016, -0.14404006,  0.97070285],
       [ 0.1765871 , -0.00626261,  2.07393708],
       [ 0.51651728,  0.36114392,  1.44351752],
       [ 1.4391849 ,  1.27966024, -0.44774117],
       [ 1.14781618,  0.82040208, -0.13253139],
       [ 0.95357036,  1.18780861, -0.05372894],
       [-0.21190452, -1.01663057,  0.02507351],
       [ 0.03090274,  0.17744065,  0.261

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)

In [12]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)
print(gnb.score(x_test,y_test))
print(cm)

0.14285714285714285
[[0 5]
 [1 1]]


In [13]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(x_train,y_train)
y_pred = bnb.predict(x_test)
print(bnb.score(x_test,y_test))
print(cm)

0.14285714285714285
[[0 5]
 [1 1]]


In [14]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train,y_train)
y_pred = mnb.predict(x_test)
print(mnb.score(x_test,y_test))
print(cm)

0.42857142857142855
[[0 5]
 [1 1]]
